.TH HELLO-WORLD 1 "December 2025" "hello-world 1.0.0" "User Commands"
.SH NAME
hello-world \- print a customizable greeting
.SH SYNOPSIS
.B hello-world
[\fIOPTION\fR]
.SH DESCRIPTION
.B hello-world
prints a greeting message. The greeting can be customized via the
configuration file at /etc/hello-world/hello.conf
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Display help and exit.
.TP
.BR \-v ", " \-\-version
Display version and exit.
.SH FILES
.TP
.I /etc/hello-world/hello.conf
Configuration file for customizing the greeting.
.TP
.I /usr/share/hello-world/hello-lib.sh
Shared library functions.
.SH EXAMPLES
.B hello-world
.br
Output: Hello, World!
.SH SEE ALSO
.BR hello-info (1)
.SH AUTHOR
OSLab Packaging Demo
