.TH HELLO-INFO 1 "December 2025" "hello-world 1.0.0" "User Commands"
.SH NAME
hello-info \- display system information
.SH SYNOPSIS
.B hello-info
[\fIOPTION\fR]
.SH DESCRIPTION
.B hello-info
displays basic system information including hostname, kernel version,
architecture, current user, and date.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Display help and exit.
.TP
.BR \-v ", " \-\-version
Display version and exit.
.TP
.BR \-s ", " \-\-short
Display short one-line output.
.SH EXAMPLES
.TP
Full output:
.B hello-info
.TP
Short output:
.B hello-info --short
.br
Output: hostname | 6.x.x | x86_64
.SH SEE ALSO
.BR hello-world (1),
.BR uname (1)
.SH AUTHOR
OSLab Packaging Demo
